name = "e2bbar-app"
main = "worker/index.js"
compatibility_date = "2026-07-03"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1

[[routes]]
pattern = "e2b.bar"
custom_domain = true

[[routes]]
pattern = "www.e2b.bar"
custom_domain = true

[[routes]]
pattern = "e2bbar.app"
custom_domain = true

[[routes]]
pattern = "www.e2bbar.app"
custom_domain = true
